#!/usr/bin/env node

/**
 * AgentPay One-Click Setup
 *
 * Deploys your own personal Fiber node + AgentPay stack.
 * One command: npx create-agentpay setup
 *
 * What this does:
 *   1. Checks Docker is installed
 *   2. Generates .env with your settings
 *   3. Starts Fiber node (your own, not official)
 *   4. Waits for node to be ready
 *   5. Shows your node pubkey (your Agent ID)
 *   6. Optionally starts LND for BTC cross-chain
 *
 * Your node connects to official bootnodes for routing,
 * but all keys, channels, and funds are yours.
 */

import { execSync, spawn } from 'node:child_process';
import { writeFileSync, existsSync, readFileSync, mkdirSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { randomBytes } from 'node:crypto';
import * as readline from 'node:readline';

// ═══════════════════════════════════════════════════════════
//  Config
// ═══════════════════════════════════════════════════════════

const BANNER = `
╔══════════════════════════════════════════════════════════╗
║                                                          ║
║   🚀 AgentPay — One-Click Fiber Node Setup              ║
║                                                          ║
║   Deploys YOUR OWN personal Fiber node.                  ║
║   All keys, channels, and funds belong to you.           ║
║                                                          ║
╚══════════════════════════════════════════════════════════╝
`;

interface SetupConfig {
  network: 'testnet' | 'mainnet';
  enableLnd: boolean;
  enableCch: boolean;
  fiberRpcPort: number;
  fiberP2pPort: number;
  password: string;
  projectDir: string;
}

// ═══════════════════════════════════════════════════════════
//  Main
// ═══════════════════════════════════════════════════════════

async function main() {
  console.log(BANNER);

  // 1. Check prerequisites
  checkPrerequisites();

  // 2. Gather config (with smart defaults)
  const config = await gatherConfig();

  // 3. Generate .env
  generateEnvFile(config);

  // 4. Generate docker-compose.yml (simplified, just what they need)
  generateDockerCompose(config);

  // 5. Start services
  startServices(config);

  // 6. Wait and show info
  await waitForNode(config);
}

// ═══════════════════════════════════════════════════════════
//  Steps
// ═══════════════════════════════════════════════════════════

function checkPrerequisites() {
  console.log('🔍 Checking prerequisites...\n');

  // Docker
  try {
    const dockerVersion = execSync('docker --version', { encoding: 'utf8' }).trim();
    console.log(`  ✅ Docker: ${dockerVersion}`);
  } catch {
    console.error('  ❌ Docker not found. Please install Docker first:');
    console.error('     https://docs.docker.com/get-docker/');
    process.exit(1);
  }

  // Docker Compose
  try {
    const composeVersion = execSync('docker compose version', { encoding: 'utf8' }).trim();
    console.log(`  ✅ Docker Compose: ${composeVersion}`);
  } catch {
    console.error('  ❌ Docker Compose not found. Please install Docker Compose.');
    process.exit(1);
  }

  console.log();
}

async function gatherConfig(): Promise<SetupConfig> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q: string): Promise<string> =>
    new Promise((resolve) => rl.question(q, resolve));

  console.log('⚙️  Configuration (press Enter for defaults)\n');

  const network = 'testnet'; // Mainnet not available yet
  console.log(`  Network: testnet (mainnet not yet available)`);

  const fiberRpcPort = parseInt(await ask('  Fiber RPC port [8227]: ') || '8227');
  const fiberP2pPort = parseInt(await ask('  Fiber P2P port [8228]: ') || '8228');

  const enableLndInput = await ask('  Enable BTC Lightning cross-chain? (y/N): ');
  const enableLnd = enableLndInput.toLowerCase() === 'y';

  // Auto-generate password
  const autoPassword = randomBytes(16).toString('hex');
  const passwordInput = await ask(`  Key encryption password [auto-generated]: `);
  const password = passwordInput || autoPassword;

  rl.close();
  console.log();

  return {
    network,
    enableLnd,
    enableCch: enableLnd, // Cch requires LND
    fiberRpcPort,
    fiberP2pPort,
    password,
    projectDir: process.cwd(),
  };
}

function generateEnvFile(config: SetupConfig) {
  const envContent = `# AgentPay Node Configuration
# Generated by: npx create-agentpay setup
# Date: ${new Date().toISOString()}

# Fiber Node
FIBER_SECRET_KEY_PASSWORD=${config.password}
FIBER_RPC_PORT=${config.fiberRpcPort}
FIBER_P2P_PORT=${config.fiberP2pPort}
FIBER_NETWORK=${config.network}

# CKB RPC (testnet)
CKB_RPC_URL=https://testnet.ckbapp.dev/

# AgentPay
AGENTPAY_FIBER_RPC_URL=http://127.0.0.1:${config.fiberRpcPort}

# BTC Lightning (optional)
ENABLE_LND=${config.enableLnd}
${config.enableLnd ? 'LND_REST_PORT=8080\nLND_GRPC_PORT=10009\nLND_P2P_PORT=9735' : '# LND disabled'}
`;

  const envPath = join(config.projectDir, '.env');
  writeFileSync(envPath, envContent);
  console.log(`📝 Generated ${envPath}`);
  console.log(`   ⚠️  Keep FIBER_SECRET_KEY_PASSWORD safe — it encrypts your private key!\n`);
}

function generateDockerCompose(config: SetupConfig) {
  let compose = `# AgentPay — Your Personal Fiber Node
# Generated by: npx create-agentpay setup

services:
  # Your personal Fiber node (official FNN v0.7.1 binary)
  fiber:
    image: ghcr.io/agentpay/fiber-node:v0.7.1
    build:
      context: .
      dockerfile: Dockerfile.fiber
    container_name: agentpay-fiber
    ports:
      - "\${FIBER_RPC_PORT:-8227}:8227"    # RPC
      - "\${FIBER_P2P_PORT:-8228}:8228"    # P2P
    volumes:
      - fiber-data:/app/data
    environment:
      - RUST_LOG=info
      - FIBER_SECRET_KEY_PASSWORD=\${FIBER_SECRET_KEY_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:18227"]
      interval: 15s
      timeout: 5s
      retries: 5
`;

  if (config.enableLnd) {
    compose += `
  # BTC Lightning Node (for cross-chain via Cch)
  lnd:
    image: lightninglabs/lnd:v0.18.0-beta
    container_name: agentpay-lnd
    volumes:
      - lnd-data:/root/.lnd
    ports:
      - "\${LND_P2P_PORT:-9735}:9735"
      - "\${LND_GRPC_PORT:-10009}:10009"
      - "\${LND_REST_PORT:-8080}:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "lncli", "--network=signet", "getinfo"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
`;
  }

  compose += `
volumes:
  fiber-data:${config.enableLnd ? '\n  lnd-data:' : ''}
`;

  const composePath = join(config.projectDir, 'docker-compose.agentpay.yml');
  writeFileSync(composePath, compose);
  console.log(`📝 Generated ${composePath}\n`);
}

function startServices(config: SetupConfig) {
  console.log('🚀 Starting your Fiber node...\n');

  const services = config.enableLnd ? 'fiber lnd' : 'fiber';
  try {
    execSync(
      `docker compose -f docker-compose.agentpay.yml up -d ${services}`,
      { cwd: config.projectDir, stdio: 'inherit' },
    );
  } catch (err: any) {
    console.error('\n❌ Failed to start services. Check Docker is running.');
    process.exit(1);
  }
  console.log();
}

async function waitForNode(config: SetupConfig) {
  console.log('⏳ Waiting for Fiber node to be ready...\n');

  const maxWait = 60; // seconds
  for (let i = 0; i < maxWait; i++) {
    try {
      const result = execSync(
        `curl -sf -X POST http://127.0.0.1:${config.fiberRpcPort} -H "Content-Type: application/json" -d '{"id":1,"jsonrpc":"2.0","method":"node_info","params":[]}'`,
        { encoding: 'utf8', timeout: 3000 },
      );
      const info = JSON.parse(result);
      const pubkey = info.result?.node_name || info.result?.public_key;

      console.log(`
╔══════════════════════════════════════════════════════════╗
║  ✅ Your Fiber Node is Running!                          ║
╠══════════════════════════════════════════════════════════╣
║                                                          ║
║  RPC:       http://127.0.0.1:${String(config.fiberRpcPort).padEnd(25)}║
║  P2P:       0.0.0.0:${String(config.fiberP2pPort).padEnd(32)}║
║  Agent ID:  ${(pubkey || 'loading...').substring(0, 42).padEnd(42)}║
║  Network:   ${config.network.padEnd(42)}║
║                                                          ║
║  Next steps:                                             ║
║  1. Fund your address with testnet CKB:                  ║
║     https://faucet.nervos.org                            ║
║  2. Open a channel with another agent                    ║
║  3. Start accepting payments!                            ║
║                                                          ║
║  Quick test:                                             ║
║  curl http://127.0.0.1:${config.fiberRpcPort}/health                       ║
║                                                          ║
╚══════════════════════════════════════════════════════════╝
`);
      return;
    } catch {
      process.stdout.write('.');
      await new Promise((r) => setTimeout(r, 1000));
    }
  }

  console.log('\n⚠️  Node is starting but not ready yet. Check: docker logs agentpay-fiber');
}

// ═══════════════════════════════════════════════════════════
//  Run
// ═══════════════════════════════════════════════════════════

main().catch((err) => {
  console.error('Setup failed:', err.message);
  process.exit(1);
});
